/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algo.sort;

import org.junit.Test;
import static org.junit.Assert.*;

public class CommonTest {
    @Test public void testSomeLibraryMethod() {
        Common classUnderTest = new Common();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
